---
title: "Report based on your visualizations"
output: 
  html_document:
    self_contained: no
---

## SQL Query

```{r echo=FALSE, message=FALSE, warning=FALSE, , results='asis', fig.height=6, fig.width=10}
library(dplyr)
library(ggplot2)
library(plotly)

par <- get(load("par"))

     df_SQL_plot <- SQL_query()
     df_SQL_plot$date <- as.Date(as.character(df_SQL_plot$date_int), "%Y%m%d")

     plot_SQL <- ggplot(df_SQL_plot, aes(x = date, y = values, col = sex)) +
                    geom_line() +
                    xlab("Date") +
                    ylab("Value") +
                    labs(col = "Sex")
    

print(plot_SQL)
```


## Map 

```{r echo=FALSE, message=FALSE, warning=FALSE, , results='asis'}
library(googleVis)
par <- get(load("par"))

eurostat_map_plot <- gvisGeoChart(
                        df_eurostat_map(), 
                        "name", 
                        "Total",
                        options = list(region = "150", 
                                  width = 1000, 
                                  height = 1000)
                    )

print(eurostat_map_plot, "chart")
```

## Time Series 

```{r echo=FALSE, message=FALSE, warning=FALSE, , results='asis', fig.height=6, fig.width=10}
library(dplyr)
library(ggplot2)
library(plotly)

eurostat_ts_plot <- ggplot(data = eurostat_ts_report(), aes(x= date, y = values)) + 
                      geom_line() +
                      scale_x_date()
  
print(eurostat_ts_plot)
```
